-- 押金表
CREATE TABLE IF NOT EXISTS deposit (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    hotel_id BIGINT NOT NULL COMMENT '酒店ID',
    deposit_no VARCHAR(32) NOT NULL COMMENT '押金单号',
    stay_id BIGINT COMMENT '入住单ID',
    reservation_id BIGINT COMMENT '预订ID',
    guest_id BIGINT NOT NULL COMMENT '客人ID',
    guest_name VARCHAR(50) NOT NULL COMMENT '客人姓名',
    room_no VARCHAR(20) COMMENT '房间号',
    amount DECIMAL(10,2) NOT NULL COMMENT '押金金额',
    payment_method VARCHAR(20) NOT NULL COMMENT '支付方式：CASH/WECHAT/ALIPAY/POS/BANK_TRANSFER',
    status VARCHAR(20) NOT NULL DEFAULT 'COLLECTED' COMMENT '押金状态：COLLECTED-已收取/REFUNDED-已退还/PARTIAL_REFUND-部分退还',
    collected_at DATETIME NOT NULL COMMENT '收取时间',
    collected_by BIGINT NOT NULL COMMENT '收取人ID',
    refunded_amount DECIMAL(10,2) DEFAULT 0 COMMENT '已退金额',
    refunded_at DATETIME COMMENT '退还时间',
    refunded_by BIGINT COMMENT '退还人ID',
    refund_method VARCHAR(20) COMMENT '退还方式',
    remark VARCHAR(500) COMMENT '备注',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁',
    PRIMARY KEY (id),
    UNIQUE KEY uk_deposit_no (deposit_no),
    KEY idx_hotel_id (hotel_id),
    KEY idx_stay_id (stay_id),
    KEY idx_guest_id (guest_id),
    KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='押金表';
